name: Test

on:
  push:
    branches:
      - main
  pull_request:
    breanches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        python: ['3.8']
        platform: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}

    - name: Install test dependencies
      run: python -m pip install -r tests/requirements.txt
    
    - name: Test
      run: python -m pytest -v